### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by waldemarhorwat** [bakkot/proposal-duplicate-named-capturing-groups#3]
Here are my review comments:

- As discussed at the plenary, please revert the change to GroupSpecifiersThatMatch
- What does "the jth capture of *R* is not undefined" in RegExpBuiltinExec mean? *R* is the RegExp object, not the filled-in list of captures.
- The logic inside RegExpBuiltinExec and MakeMatchIndicesIndexPairArray can now create the same properties multiple times. That seems ok because we know the objects are configurable at this point, but it may be worth commenting on.

**Comment by bakkot** [comment]
> As discussed at the plenary, please revert the change to GroupSpecifiersThatMatch

Done in https://github.com/tc39/ecma262/pull/2721/commits/7bf3f400e5004842633ec1c83f9b8474b756fa75

> What does "the jth capture of R is not undefined" in RegExpBuiltinExec mean? R is the RegExp object, not the filled-in list of captures.

Changed to `the _j_<sup>th</sup> element of _R_'s _captures_ List` in https://github.com/tc39/ecma262/pull/2721/commits/882bed3fc2fcfd06b1d731291014a7cd2e1b921d

> The logic inside RegExpBuiltinExec and MakeMatchIndicesIndexPairArray can now create the same properties multiple times

Done in https://github.com/tc39/ecma262/pull/2721/commits/5af2ca07ab4c3bffeb11fc084ae08d7376f81104.

This should only happen when no group with the name of interest matched, which I've called out in the NOTEs. If you see a way for it to happen otherwise, that's a bug.

**Comment by waldemarhorwat** [comment]
Also, the order in which the named properties get created now varies for different runs of the same regexp. Whether that's a problem or not is a matter for discussion, but if we want to do that, that's something that we should do consciously.

**Comment by waldemarhorwat** [comment]
> > What does "the jth capture of R is not undefined" in RegExpBuiltinExec mean? R is the RegExp object, not the filled-in list of captures.
> 
> Changed to `the _j_<sup>th</sup> element of _R_'s _captures_ List` in [tc39/ecma262@882bed3](https://github.com/tc39/ecma262/commit/882bed3fc2fcfd06b1d731291014a7cd2e1b921d)

That's still incorrect. _R_ is the _RegExp_ object, which does not have a _captures_ List.

**Comment by waldemarhorwat** [comment]
I think you want _r_, not _R_. They're different variables.

**Comment by bakkot** [comment]
> Also, the order in which the named properties get created now varies for different runs of the same regexp. Whether that's a problem or not is a matter for discussion, but if we want to do that, that's something that we should do consciously.

True. It's probably easier on engines for the order to be deterministic (matching the order in which each name first appears), and I don't think it's like to affect users. I've changed that in https://github.com/tc39/ecma262/pull/2721/commits/34545fecc5583a35dbaa7b0f0f5eb532dd9faa63.

> I think you want _r_, not _R_. They're different variables.

Sorry, yes, I fixed that in a [subsequent commit](https://github.com/tc39/ecma262/pull/2721/commits/2cbe509b27529b19f5f3cc1d4deb7af5cfe5cb52).

**Comment by iainireland** [comment]
> > Also, the order in which the named properties get created now varies for different runs of the same regexp. Whether that's a problem or not is a matter for discussion, but if we want to do that, that's something that we should do consciously.
> 
> True. It's probably easier on engines for the order to be deterministic (matching the order in which each name first appears), and I don't think it's like to affect users. I've changed that in [tc39/ecma262@34545fe](https://github.com/tc39/ecma262/commit/34545fecc5583a35dbaa7b0f0f5eb532dd9faa63).

I came here intending to file an issue about this, so I can confirm that at least from SpiderMonkey's point of view it is significantly nicer (and more performant) if the order in which properties are created remains deterministic. Right now, for each regexp, we can precompute the shape of the `groups` object, as well as an array of indices mapping each slot of that object to the corresponding capture group. Duplicate groups mean that we'll need a slightly more sophisticated mechanism for figuring out which result goes in which slot, but if the property order is deterministic then nothing else has to change.

**Comment by bakkot** [comment]
This proposal is now stage 3, with the comments above addressed. Thank you for your review.
